### ISSUE TITLE
Not working on mozzilla

### ISSUE THREAD

**Issue by mathieuarthur** [RedEdge967/HACKZILLA#1]
Hey, just to reach you and say that the project seems not to work on mozilla (the online version didn't tried the local one)

**Comment by RedEdge967** [comment]
I will check soon

**Comment by RedEdge967** [comment]
Hi @mathieuarthur I just checked it and it didn't work on all browsers because of a buggy script. I changed it. now it works on all browsers. thanks for the issue

**Comment by RedEdge967** [comment]
will release a new local version
